- platform: xiaomi_cloud_map_extractor
  name: Vacuum Map
  host: 192.168.1.222
  country: "de"
  token: !env_var HOME_ASSISTANT_VACUUM_TOKEN
  username: !env_var HOME_ASSISTANT_XIAOMI_USERNAME
  password: !env_var HOME_ASSISTANT_XIAOMI_PASSWORD
  draw: ['all']
  attributes:
    - calibration_points
    - charger
    - cleaned_rooms
    - country
    - goto
    - goto_path
    - goto_predicted_path
    - image
    - is_empty
    - map_name
    - no_go_areas
    - no_mopping_areas
    - obstacles
    - ignored_obstacles
    - obstacles_with_photo
    - ignored_obstacles_with_photo
    - path
    - room_numbers
    - rooms
    - vacuum_position
    - vacuum_room
    - vacuum_room_name
    - walls
    - zones
