- platform: zwave

- platform: generic_thermostat
  name: Kitchen Thermostat
  heater: switch.kitchen_heater
  target_sensor: sensor.kitchen_temperature
  away_temp: 20
  keep_alive:
    minutes: 10

