- platform: template
  covers:
    living_room:
      device_class: blind
      friendly_name: "Cover"
      optimistic: true
      open_cover:
        service: cover.set_cover_position
        data:
          entity_id: cover.living_room_controller
          position: 100
      close_cover:
        service: cover.set_cover_position
        data:
          entity_id: cover.living_room_controller
          position: 0