- platform: alexa_media
  name: alexa_media

# Push messages using gotify server https://gotify.net/docs/pushmsg
- name: gotify
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_GOTIFY_ENDPOINT

- name: lunching
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_GOTIFY_LUNCHING_ENDPOINT

- name: ola
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_OLA_GOTIFY

- name: all
  platform: group
  services:
    - service: ola
    - service: gotify
    - service: tv

- name: tortuga
  platform: matrix
  default_room: !env_var HOME_ASSISTANT_MATRIX_ROOM
