- platform: alexa_media
  name: alexa_media

# Push messages using gotify server https://gotify.net/docs/pushmsg
- name: gotify
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_GOTIFY_ENDPOINT

- name: lunching
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_GOTIFY_LUNCHING_ENDPOINT

- name: ola
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_OLA_GOTIFY

- name: all
  platform: group
  services:
    - service: ola
    - service: gotify
    - service: tv

- name: tortuga
  platform: matrix
  default_room: !env_var HOME_ASSISTANT_MATRIX_ROOM

- name: twitter
  platform: twitter
  consumer_key: !env_var TWITTER_API_KEY
  consumer_secret: !env_var TWITTER_CONSUMER_KEY
  access_token: !env_var TWITTER_ACCESS_TOKEN
  access_token_secret: !env_var TWITTER_ACCESS_TOKEN_SECRET
