- platform: template
  switches:
    living_room_heater:
      value_template: "{{ states.climate.living_room.attributes.temperature == 28 }}"
      turn_on:
        service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: 28
      turn_off:
        service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: 7
    bedroom_heater:
      value_template: "{{ states.climate.bedroom.attributes.temperature == 28 }}"
      turn_on:
        service: climate.set_temperature
        data:
          entity_id: climate.bedroom
          temperature: 28
      turn_off:
        service: climate.set_temperature
        data:
          entity_id: climate.bedroom
          temperature: 7
    kitchen_heater:
      value_template: "{{ states.climate.kitchen.attributes.temperature == 28 }}"
      turn_on:
        service: climate.set_temperature
        data:
          entity_id: climate.kitchen
          temperature: 28
      turn_off:
        service: climate.set_temperature
        data:
          entity_id: climate.kitchen
          temperature: 7

- platform: flux
  lights:
    - light.arek_szafka
    - light.ola_szafka
  brightness: 83
  mode: mired
  disable_brightness_adjust: true
  start_colortemp: 3500
  sunset_colortemp: 2800
  stop_colortemp: 2200

- platform: mqtt
  name: Dispense Food
  command_topic: "home/kitchen/puss_feeder/dispense_food/set"
  state_topic: "home/kitchen/puss_feeder/dispense_food"

- platform: template
  switches:
    giggid:
      value_template: "{{ is_state('input_boolean.giggid', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.giggid
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.giggid
    pizza:
      value_template: "{{ is_state('input_boolean.pizza', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.pizza
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.pizza
