# All media services, that don't need to be always online
version: '3.5'

services:
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    environment: 
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/snarr:/config
      - /mnt/MoviesAndTV:/tv
      - /home/downloads:/downloads

  plex:
    network_mode: host
    image: plexinc/pms-docker:latest
    env_file:
      - .env.plex
    volumes:
      - .docker/data/plex/config:/config
      - .docker/data/plex/transcode:/transcode
      - /mnt:/data
