version: '3'
services:
  zwave:
    build:
      context: ./zwave
      dockerfile: Dockerfile
    network_mode: host
    security_opt:
      - seccomp:unconfined
    devices:
      - "/dev/ttyACM0"
    volumes:
      - .docker/data/zwavejs/cache:/cache
    ports:
      - "9312:3000"
    restart: unless-stopped
    env_file:
      - '.env.zwave'
