# Small laboratory
version: '3.5'

services:
  tor:
    restart: unless-stopped
    build: ./tor/
    network_mode: host
    volumes:
      - .docker/data/tor:/data
  speedtest:
    image: macbury/speedtest:latest
    env_file:
      - '.env.speedtest'
    ports:
      - 6888:80
