- id: '1596707193800'
  alias: Send door code near work
  description: ''
  trigger:
  - entity_id: device_tracker.arek
    event: enter
    platform: zone
    zone: zone.codesthq
  condition: []
  action:
  - data:
      message: 6 kluczyk 7153
      title: Kod do bramy
    service: notify.gotify
  mode: single
- id: '1597867269400'
  alias: If Arek weight change announce it to everybody in home
  description: ''
  trigger:
  - above: '70'
    entity_id: sensor.arek_weight
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Your weight is {{states.sensor.arek_weight.state}} kilo, so you are
        still fat.
      title: Weight
    service: notify.gotify
  mode: single
- id: '1597870082700'
  alias: Do not disturb alexa if nobody home or it is night
  description: ''
  trigger:
  - entity_id: group.family
    from: Home
    platform: state
    to: Away
  - at: '23:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.everywhere_do_not_disturb_switch
    service: switch.turn_on
  mode: single
- id: '1597870159000'
  alias: Enable alexa devices at morning or if somebody is coming back
  description: ''
  trigger:
  - entity_id: group.family
    from: Away
    platform: state
    to: Home
  - at: '7:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.everywhere_do_not_disturb_switch
    service: switch.turn_off
  mode: single
- id: '1598889031447'
  alias: Turn off light for xiaomi fan
  description: ''
  trigger:
  - at: 0:02
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: fan.bedroom_air_purifier
    service: xiaomi_miio.fan_set_led_brightness
  mode: single
- id: '1600170239579'
  alias: Heal network
  description: ''
  trigger:
  - at: '4:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: zwave.heal_network
  mode: single
- id: '1601236736500'
  alias: Pause TV if Arek has a Call
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.arek_phone_state
    to: ringing
    from: idle
  - platform: state
    entity_id: sensor.arek_phone_state
    from: idle
    to: offhook
  condition:
  - condition: state
    entity_id: person.arek
    state: home
  action:
  - service: media_player.media_pause
    data: {}
    entity_id: media_player.tv
  mode: single
- id: '1601237413600'
  alias: Pause TV if Arek has a Call (Duplicate)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.olas8_stan_telefonu
    to: ringing
    from: idle
  - platform: state
    entity_id: sensor.olas8_stan_telefonu
    from: idle
    to: offhook
  condition:
  - condition: state
    entity_id: person.ola
    state: home
  action:
  - service: media_player.media_pause
    data: {}
    entity_id: media_player.tv
  mode: single
- id: '1601668124100'
  alias: Prysznic
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: notify.all
    data:
      message: Prysznic!
  mode: single
- id: '1606050672600'
  alias: Ola wyjedża od Jarosa
  description: ''
  trigger:
  - platform: zone
    entity_id: person.ola
    zone: zone.ranczo_klimkow
    event: leave
  condition: []
  action:
  - service: notify.alexa_media_living_room
    data:
      message: Ola is leaving Klimki House
      data:
        type: announce
        method: all
  - delay: '10'
  - service: notify.alexa_media_kitchen
    data:
      message: Ola is leaving Klimki House
      data:
        type: announce
        method: all
  mode: single
- id: '1606652899700'
  alias: Ola wyjedża od Dzidki
  description: ''
  trigger:
  - platform: zone
    entity_id: person.ola
    zone: zone.dzidka
    event: leave
  condition: []
  action:
  - service: notify.alexa_media_living_room
    data:
      message: Ola is leaving Dzidka House
      data:
        type: announce
        method: all
  - delay: '10'
  - service: notify.alexa_media_kitchen
    data:
      message: Ola is leaving Dzidka House
      data:
        type: announce
        method: all
  mode: single
- id: '1607521396700'
  alias: Humidifier is in dry mode
  description: Tell people in the house that humidifier is out of water
  trigger:
  - platform: state
    entity_id: fan.living_room_humidifier
    attribute: dry
    from: 'False'
    to: 'True'
  condition: []
  action:
  - service: notify.all
    data:
      title: Nawilżacz
      message: Uzupełnij wodę w nawilżaczu!
  mode: single
- id: '1607889011300'
  alias: Switch on choinka
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.christmas_tree
  mode: single
- id: '1607889099900'
  alias: Switch off choinka
  description: ''
  trigger:
  - platform: time
    at: '23:59'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.christmas_tree
  mode: single
