- id: '1596707193800'
  alias: Send door code near work
  description: ''
  trigger:
  - entity_id: device_tracker.arek
    event: enter
    platform: zone
    zone: zone.codesthq
  condition: []
  action:
  - data:
      message: 6 kluczyk 7153
      title: Kod do bramy
    service: notify.gotify
  mode: single
- id: '1597867269400'
  alias: If Arek weight change announce it to everybody in home
  description: ''
  trigger:
  - above: '70'
    entity_id: sensor.arek_weight
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Your weight is {{states.sensor.arek_weight.state}} kilo, so you are
        still fat.
      title: Weight
    service: notify.gotify
  mode: single
- id: '1597870082700'
  alias: Do not disturb alexa if nobody home or it is night
  description: ''
  trigger:
  - entity_id: group.family
    from: Home
    platform: state
    to: Away
  - at: '23:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.everywhere_do_not_disturb_switch
    service: switch.turn_on
  mode: single
- id: '1597870159000'
  alias: Enable alexa devices at morning or if somebody is coming back
  description: ''
  trigger:
  - entity_id: group.family
    from: Away
    platform: state
    to: Home
  - at: '7:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.everywhere_do_not_disturb_switch
    service: switch.turn_off
  mode: single
- id: '1598889031447'
  alias: Turn off light for xiaomi fan
  description: ''
  trigger:
  - at: 0:02
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: fan.bedroom_air_purifier
    service: xiaomi_miio.fan_set_led_brightness
  mode: single
- id: '1600170239579'
  alias: Heal network
  description: ''
  trigger:
  - at: '4:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: zwave.heal_network
  mode: single
- id: '1601236736500'
  alias: Pause TV if Arek has a Call
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.arek_phone_state
    to: ringing
    from: idle
  - platform: state
    entity_id: sensor.arek_phone_state
    from: idle
    to: offhook
  condition:
  - condition: state
    entity_id: person.arek
    state: home
  action:
  - service: media_player.media_pause
    data: {}
    entity_id: media_player.tv
  mode: single
- id: '1601237413600'
  alias: Pause TV if Arek has a Call (Duplicate)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.olas8_stan_telefonu
    to: ringing
    from: idle
  - platform: state
    entity_id: sensor.olas8_stan_telefonu
    from: idle
    to: offhook
  condition:
  - condition: state
    entity_id: person.ola
    state: home
  action:
  - service: media_player.media_pause
    data: {}
    entity_id: media_player.tv
  mode: single
- id: '1601668124100'
  alias: Prysznic
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: notify.all
    data:
      message: Prysznic!
  mode: single
- id: '1606050672600'
  alias: Ola wyjedża od Jarosa
  description: ''
  trigger:
  - platform: zone
    entity_id: person.ola
    zone: zone.ranczo_klimkow
    event: leave
  condition: []
  action:
  - service: notify.alexa_media_living_room
    data:
      message: Ola is leaving Klimki House
      data:
        type: announce
        method: all
  - delay: '10'
  - service: notify.alexa_media_kitchen
    data:
      message: Ola is leaving Klimki House
      data:
        type: announce
        method: all
  mode: single
- id: '1606652899700'
  alias: Ola wyjedża od Dzidki
  description: ''
  trigger:
  - platform: zone
    entity_id: person.ola
    zone: zone.dzidka
    event: leave
  condition: []
  action:
  - service: notify.alexa_media_living_room
    data:
      message: Ola is leaving Dzidka House
      data:
        type: announce
        method: all
  - delay: '10'
  - service: notify.alexa_media_kitchen
    data:
      message: Ola is leaving Dzidka House
      data:
        type: announce
        method: all
  mode: single
- id: '1607521396700'
  alias: Humidifier is in dry mode
  description: Tell people in the house that humidifier is out of water
  trigger:
  - platform: state
    entity_id: fan.living_room_humidifier
    attribute: dry
    from: 'False'
    to: 'True'
  condition: []
  action:
  - service: notify.all
    data:
      title: Nawilżacz
      message: Uzupełnij wodę w nawilżaczu!
  mode: single
- id: '1607889011300'
  alias: Switch on choinka
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.christmas_tree
  mode: single
- id: '1607889099900'
  alias: Switch off choinka
  description: ''
  trigger:
  - platform: time
    at: '23:59'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.christmas_tree
  mode: single
- id: '1609398359663'
  alias: Switch off light balls
  description: ''
  trigger:
  - platform: time
    at: '8:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.hall_light
  mode: single
- id: '1610810175829'
  alias: Ola wyjedża od Anki
  description: ''
  trigger:
  - platform: zone
    entity_id: person.ola
    zone: zone.anka
    event: leave
  condition: []
  action:
  - service: notify.alexa_media_living_room
    data:
      message: Ola is leaving Anka House
      data:
        type: announce
        method: all
  - delay: '10'
  - service: notify.alexa_media_kitchen
    data:
      message: Ola is leaving Anka House
      data:
        type: announce
        method: all
  mode: single
- id: '1612103094478'
  alias: Bedroom window opened too long
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_window
    from: 'off'
    to: 'on'
    for: '1:10:00'
  condition: []
  action:
  - service: notify.all
    data:
      message: Okno w sypialni otwarte zbyt długo
  mode: single
- id: '1616752611416'
  alias: Lazy switch off automations
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    entity_id: automation.inform_me_if_number_of_beerbug_patients_changed
  mode: single
- id: '1620048655385'
  alias: Ola is in Galeria krakowska
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.ola
      zone_entity: zone.galeria_krakowka
      notify_device: 3465c7e083aa4509b0ca3a5e796fc854
- id: '1620403076688'
  alias: Switch mosquitto killer in bedroom on before going to sleep
  description: ''
  trigger: []
  condition: []
  action: []
  mode: single
- id: '1620403128707'
  alias: Switch off mosquitto killer at morning
  description: ''
  trigger: []
  condition: []
  action: []
  mode: single
- id: '1642450576503'
  alias: Tag Hulajnoga is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: cb152ef9-080d-4aae-9cbc-e15a8b241f99
  condition: []
  action:
  - service: notify.mobile_app_arek
    data:
      message: command_screen_on
      title: keep_screen_on
  - service: notify.mobile_app_arek
    data:
      message: command_activity
      title: adriandp.m365dashboard
      data:
        channel: adriandp.m365dashboard
        tag: android.intent.action.VIEW
  mode: single
- id: '1645086358331'
  alias: Open Cover at night
  description: Open cover at night for better ventilation
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: state
    entity_id: light.tv_stand
    for:
      hours: 0
      minutes: 15
      seconds: 0
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.tv_stand
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: 05:00:00
  action:
  - service: cover.set_cover_position
    data:
      position: 70
    target:
      entity_id: cover.living_room_controller
  mode: single
- id: '1646553657957'
  alias: Inform about wibor change
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.wibor_6m
  condition: []
  action:
  - service: notify.mobile_app_arek
    data:
      title: Zmiana w wiborze
      message: 'Wibor 3M: {{ states.sensor.wibor_3m.state }}% Wibor 6M: {{ states.sensor.wibor_6m.state
        }}% Wibor 1R: {{ states.sensor.wibor_1r.state }}%

        '
  mode: single
- id: '1648111535506'
  alias: Remind me to charge my scooter
  description: ''
  trigger:
  - platform: state
    entity_id: person.arek
    to: home
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: state
    entity_id: person.arek
    to: chargify
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_arek
    data:
      title: Podłącz chulajnoge do ładowania
      message: Podłącz chulajnoge do ładowania
  mode: single
