- platform: integration
  source: sensor.power_consumption
  name: energy_spent
  unit_prefix: k
  round: 4

- platform: integration
  source: sensor.cool_as_ice_energy_current
  name: "Air condition energy used"
  unit_prefix: k
  round: 4
