- alias: Close blinds on sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.family'
        state: 'home'
  action:
    - service: cover.close_cover
      data:
        entity_id: cover.living_room

- alias: Switch on tv stand room light 
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.family'
        state: 'home'
      - condition: state
        entity_id: light.main
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.tv_stand

- alias: Open blinds in morning
  trigger:
    - platform: time
      at: '7:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.family'
        state: 'home'
  action:
    - service: cover.open_cover
      data:
        entity_id: cover.living_room
    - service: light.turn_off
      entity_id: light.arek_szafka
    - service: light.turn_off
      entity_id: light.ola_szafka
      
