- alias: Notify me that my work is done
  trigger:
    platform: numeric_state
    entity_id: sensor.arek_czas_pracy
    value_template: '{{ state.attributes.minutes }}'
    above: 420
  condition:
    - condition: state
      entity_id: person.arek
      state: codesthq
  action:
    - service: notify.gotify
      data:
        title: 'Praca'
        message: "Fajrant, czas spierdalać do domu!"

- alias: Notify me if wife is near work
  trigger:
    platform: state
    entity_id: person.ola
    to: 'chargify'
  action:
    - service: notify.gotify
      data:
        title: 'Praca'
        message: "Ola jest pod biurem"

- alias: Notify wife that I left work
  trigger:
    - platform: state
      entity_id: person.arek
      from: 'chargify'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: person.ola
      state: home
  action:
    - service: notify.alexa_media_living_room
      data:
        message: "Wife, Your housband left work"
        data:
          type: announce
          method: all
    - delay: '00:00:45'
    - service: notify.all
      data:
        message: '@Ola, Monsz wyszedł z roboty'

- alias: Inform about lunching order
  trigger:
    platform: state
    entity_id: person.arek
    to: 'chargify'
    for: '00:05:00'
  condition:
    - condition: state
      entity_id: sensor.arek_jedzenie
      state: 'off'
  action:
    - service: notify.lunching
      data:
        message: '@Arek Lunching mutafaka!'

- alias: Tell me what food will be in 30 minutes delivered to my at work
  trigger:
    platform: numeric_state
    entity_id: sensor.arek_jedzenie
    value_template: '{{  states.sensor.arek_jedzenie.attributes.time_left }}'
    below: 1800
  condition:
    - condition: state
      entity_id: person.arek
      state: chargify
    - condition: state
      entity_id: sensor.arek_jedzenie
      state: 'on'
  action:
    - service: notify.lunching
      data_template:
        title: 'Praca'
        message: "Za pół godziny, przy dobrych mocach posejdona strawa twa będzie {{ states.sensor.arek_jedzenie.attributes.meal }}"

- alias: Notify me that food was delivered
  trigger:
    - platform: state
      entity_id: sensor.arek_jedzenie
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: person.arek
      state: chargify
  action:
    - service: notify.lunching
      data_template:
        title: 'Praca'
        message: >
          Swarożycu uświęć te ofiarne napoje i strawy,
          by Twej mocy nabrały i byśmy spożywając je bliżsi Bogom byli.
          Przyjm w swe ciało zioła święte, niech oczyszczą to miejsce
          i przyniosą wszystko to co dobre, dla nas i dla naszych rodzin.
